In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("StudentsPerformance.csv")

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
print("First 10 Rows")
display(df.head(10))

print("Last 10 Rows")
display(df.tail(10))

First 10 Rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

Last 10 Rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nInfo:")
df.info()

Shape: (1000, 8)

Columns:
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [5]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [6]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [7]:
df.loc[5, "math score"] = np.nan
df.loc[15, "reading score"] = np.nan
df.loc[25, "writing score"] = np.nan

df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     1
reading score                  1
writing score                  1
dtype: int64

In [8]:
df["math score"] = df["math score"].fillna(df["math score"].mean())

df["reading score"] = df["reading score"].fillna(df["reading score"].mean())

df["writing score"] = df["writing score"].fillna(df["writing score"].mean())

df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [9]:
print("Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

Duplicate Rows: 0

In [10]:
print("Gender")
print(df["gender"].unique())

print("\nLunch")
print(df["lunch"].unique())

print("\nTest Preparation")
print(df["test preparation course"].unique())

print("\nRace")
print(df["race/ethnicity"].unique())

Gender
['female' 'male']

Lunch
['standard' 'free/reduced']

Test Preparation
['none' 'completed']

Race
['group B' 'group C' 'group A' 'group D' 'group E']

In [11]:
df["Total Score"] = (
    df["math score"] +
    df["reading score"] +
    df["writing score"]
)

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0
1,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,278.0
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,148.0
4,male,group C,some college,standard,none,76.0,78.0,75.0,229.0

In [12]:
df["Average Score"] = df["Total Score"] / 3

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0,72.666667
1,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0,82.333333
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,278.0,92.666667
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,148.0,49.333333
4,male,group C,some college,standard,none,76.0,78.0,75.0,229.0,76.333333

In [13]:
df["Percentage"] = (df["Total Score"] / 300) * 100

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0,72.666667,72.666667
1,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0,82.333333,82.333333
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,278.0,92.666667,92.666667
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,148.0,49.333333,49.333333
4,male,group C,some college,standard,none,76.0,78.0,75.0,229.0,76.333333,76.333333

In [14]:
def grade(percent):
    if percent >= 90:
        return "A+"
    elif percent >= 80:
        return "A"
    elif percent >= 70:
        return "B"
    elif percent >= 60:
        return "C"
    else:
        return "D"

df["Grade"] = df["Percentage"].apply(grade)

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage,Grade
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0,72.666667,72.666667,B
1,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0,82.333333,82.333333,A
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,278.0,92.666667,92.666667,A+
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,148.0,49.333333,49.333333,D
4,male,group C,some college,standard,none,76.0,78.0,75.0,229.0,76.333333,76.333333,B

In [15]:
df["Result"] = np.where(
    (df["math score"] >= 35) &
    (df["reading score"] >= 35) &
    (df["writing score"] >= 35),
    "Pass",
    "Fail"
)

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage,Grade,Result
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0,72.666667,72.666667,B,Pass
1,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0,82.333333,82.333333,A,Pass
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,278.0,92.666667,92.666667,A+,Pass
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,148.0,49.333333,49.333333,D,Pass
4,male,group C,some college,standard,none,76.0,78.0,75.0,229.0,76.333333,76.333333,B,Pass

In [16]:
df.insert(0, "Student_ID", range(1, len(df) + 1))

df.head()

,Student_ID,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage,Grade,Result
0,1,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0,72.666667,72.666667,B,Pass
1,2,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0,82.333333,82.333333,A,Pass
2,3,female,group B,master's degree,standard,none,90.0,95.0,93.0,278.0,92.666667,92.666667,A+,Pass
3,4,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,148.0,49.333333,49.333333,D,Pass
4,5,male,group C,some college,standard,none,76.0,78.0,75.0,229.0,76.333333,76.333333,B,Pass

In [17]:
print("Total Students:", len(df))

print("\nGender Count")
print(df["gender"].value_counts())

print("\nAverage Math Score:", round(df["math score"].mean(), 2))
print("Average Reading Score:", round(df["reading score"].mean(), 2))
print("Average Writing Score:", round(df["writing score"].mean(), 2))

Total Students: 1000

Gender Count
gender
female    518
male      482
Name: count, dtype: int64

Average Math Score: 66.08
Average Reading Score: 69.16
Average Writing Score: 68.05

In [18]:
highest = df.loc[df["Total Score"].idxmax()]

highest

Student_ID                                   459
gender                                    female
race/ethnicity                           group E
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                 100.0
reading score                              100.0
writing score                              100.0
Total Score                                300.0
Average Score                              100.0
Percentage                                 100.0
Grade                                         A+
Result                                      Pass
Name: 458, dtype: object

In [19]:
lowest = df.loc[df["Total Score"].idxmin()]

lowest

Student_ID                                   60
gender                                   female
race/ethnicity                          group C
parental level of education    some high school
lunch                              free/reduced
test preparation course                    none
math score                                  0.0
reading score                              17.0
writing score                              10.0
Total Score                                27.0
Average Score                               9.0
Percentage                                  9.0
Grade                                         D
Result                                     Fail
Name: 59, dtype: object

In [20]:
df["Result"].value_counts()

Result
Pass    971
Fail     29
Name: count, dtype: int64

In [21]:
df.groupby("gender")[["math score","reading score","writing score"]].mean().round(2)

        math score  reading score  writing score
gender
female       63.62          72.60          72.47
male         68.73          65.47          63.30

In [22]:
df.groupby("lunch")[["math score","reading score","writing score"]].mean().round(2)

              math score  reading score  writing score
lunch
free/reduced       58.92          64.65          63.01
standard           70.03          71.65          70.82

In [23]:
df.groupby("test preparation course")[["math score","reading score","writing score"]].mean().round(2)

                         math score  reading score  writing score
test preparation course
completed                     69.70          73.89          74.42
none                          64.07          66.53          64.50

In [24]:
df.groupby("race/ethnicity")[["math score","reading score","writing score"]].mean().round(2)

                math score  reading score  writing score
race/ethnicity
group A              61.63          64.67          62.63
group B              63.43          67.35          65.60
group C              64.46          69.09          67.83
group D              67.36          70.03          70.15
group E              73.82          73.03          71.41

In [25]:
df.groupby("parental level of education")[["math score","reading score","writing score"]].mean().round(2)

                             math score  reading score  writing score
parental level of education
associate's degree                67.86          70.93          69.90
bachelor's degree                 69.39          73.00          73.38
high school                       62.14          64.70          62.45
master's degree                   69.75          75.37          75.61
some college                      67.13          69.46          68.84
some high school                  63.50          66.91          64.89

In [26]:
top10 = df.sort_values(by="Total Score", ascending=False)

top10.head(10)

,Student_ID,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage,Grade,Result
916,917,male,group E,bachelor's degree,standard,completed,100.0,100.0,100.0,300.0,100.000000,100.000000,A+,Pass
458,459,female,group E,bachelor's degree,standard,none,100.0,100.0,100.0,300.0,100.000000,100.000000,A+,Pass
962,963,female,group E,associate's degree,standard,none,100.0,100.0,100.0,300.0,100.000000,100.000000,A+,Pass
114,115,female,group E,bachelor's degree,standard,completed,99.0,100.0,100.0,299.0,99.666667,99.666667,A+,Pass
179,180,female,group D,some high school,standard,completed,97.0,100.0,100.0,297.0,99.000000,99.000000,A+,Pass
712,713,female,group D,some college,standard,none,98.0,100.0,99.0,297.0,99.000000,99.000000,A+,Pass
165,166,female,group C,bachelor's degree,standard,completed,96.0,100.0,100.0,296.0,98.666667,98.666667,A+,Pass
625,626,male,group D,some college,standard,completed,100.0,97.0,99.0,296.0,98.666667,98.666667,A+,Pass
903,904,female,group D,bachelor's degree,free/reduced,completed,93.0,100.0,100.0,293.0,97.666667,97.666667,A+,Pass
149,150,male,group E,associate's degree,free/reduced,completed,100.0,100.0,93.0,293.0,97.666667,97.666667,A+,Pass

In [27]:
bottom10 = df.sort_values(by="Total Score")

bottom10.head(10)

,Student_ID,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage,Grade,Result
59,60,female,group C,some high school,free/reduced,none,0.0,17.0,10.0,27.0,9.000000,9.000000,D,Fail
980,981,female,group B,high school,free/reduced,none,8.0,24.0,23.0,55.0,18.333333,18.333333,D,Fail
596,597,male,group B,high school,free/reduced,none,30.0,24.0,15.0,69.0,23.000000,23.000000,D,Fail
327,328,male,group A,some college,free/reduced,none,28.0,23.0,19.0,70.0,23.333333,23.333333,D,Fail
76,77,male,group E,some high school,standard,none,30.0,26.0,22.0,78.0,26.000000,26.000000,D,Fail
17,18,female,group B,some high school,free/reduced,none,18.0,32.0,28.0,78.0,26.000000,26.000000,D,Fail
601,602,female,group C,high school,standard,none,29.0,29.0,30.0,88.0,29.333333,29.333333,D,Fail
787,788,female,group B,some college,standard,none,19.0,38.0,32.0,89.0,29.666667,29.666667,D,Fail
338,339,female,group B,some high school,free/reduced,none,24.0,38.0,27.0,89.0,29.666667,29.666667,D,Fail
211,212,male,group C,some college,free/reduced,none,35.0,28.0,27.0,90.0,30.000000,30.000000,D,Fail

In [28]:
attendance = pd.DataFrame({
    "Student_ID": df["Student_ID"],
    "Attendance": np.random.randint(60, 101, len(df))
})

attendance.head()

   Student_ID  Attendance
0           1          64
1           2          87
2           3          98
3           4          98
4           5          68

In [29]:
attendance.to_csv("student_attendance.csv", index=False)

print("Attendance dataset saved.")

Attendance dataset saved.

In [30]:
merged = pd.merge(
    df,
    attendance,
    on="Student_ID",
    how="left"
)

merged.head()

,Student_ID,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage,Grade,Result,Attendance
0,1,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0,72.666667,72.666667,B,Pass,64
1,2,female,group C,some college,standard,completed,69.0,90.0,88.0,247.0,82.333333,82.333333,A,Pass,87
2,3,female,group B,master's degree,standard,none,90.0,95.0,93.0,278.0,92.666667,92.666667,A+,Pass,98
3,4,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,148.0,49.333333,49.333333,D,Pass,98
4,5,male,group C,some college,standard,none,76.0,78.0,75.0,229.0,76.333333,76.333333,B,Pass,68

In [31]:
merged.groupby("Grade")["Attendance"].mean().round(2)

Grade
A     80.51
A+    80.56
B     79.23
C     81.02
D     81.10
Name: Attendance, dtype: float64

In [32]:
merged[merged["Attendance"] < 75]

,Student_ID,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average Score,Percentage,Grade,Result,Attendance
0,1,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,218.0,72.666667,72.666667,B,Pass,64
4,5,male,group C,some college,standard,none,76.0,78.0,75.0,229.0,76.333333,76.333333,B,Pass,68
6,7,female,group B,some college,standard,completed,88.0,95.0,92.0,275.0,91.666667,91.666667,A+,Pass,66
10,11,male,group C,associate's degree,standard,none,58.0,54.0,52.0,164.0,54.666667,54.666667,D,Pass,60
11,12,male,group D,associate's degree,standard,none,40.0,52.0,43.0,135.0,45.000000,45.000000,D,Pass,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,988,male,group E,some high school,standard,completed,81.0,75.0,76.0,232.0,77.333333,77.333333,B,Pass,72
988,989,female,group A,some high school,free/reduced,none,44.0,45.0,45.0,134.0,44.666667,44.666667,D,Pass,67
990,991,male,group E,high school,free/reduced,completed,86.0,81.0,75.0,242.0,80.666667,80.666667,A,Pass,64
991,992,female,group B,some high school,standard,completed,65.0,82.0,78.0,225.0,75.000000,75.000000,B,Pass,69
996,997,male,group C,high school,free/reduced,none,62.0,55.0,55.0,172.0,57.333333,57.333333,D,Pass,66

In [33]:
merged.to_csv("cleaned_students.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [34]:
print("=" * 50)
print("STUDENT PERFORMANCE REPORT")
print("=" * 50)

print(f"Total Students : {len(merged)}")

print(f"Male Students : {(merged['gender']=='male').sum()}")
print(f"Female Students : {(merged['gender']=='female').sum()}")

print(f"\nAverage Math Score : {merged['math score'].mean():.2f}")
print(f"Average Reading Score : {merged['reading score'].mean():.2f}")
print(f"Average Writing Score : {merged['writing score'].mean():.2f}")

print(f"\nHighest Percentage : {merged['Percentage'].max():.2f}")
print(f"Lowest Percentage : {merged['Percentage'].min():.2f}")

print(f"\nPass Students : {(merged['Result']=='Pass').sum()}")
print(f"Fail Students : {(merged['Result']=='Fail').sum()}")

print("\nGrade Distribution")
print(merged["Grade"].value_counts())

print("=" * 50)

==================================================
STUDENT PERFORMANCE REPORT
==================================================
Total Students : 1000
Male Students : 482
Female Students : 518

Average Math Score : 66.08
Average Reading Score : 69.16
Average Writing Score : 68.05

Highest Percentage : 100.00
Lowest Percentage : 9.00

Pass Students : 971
Fail Students : 29

Grade Distribution
Grade
D     285
B     261
C     256
A     146
A+     52
Name: count, dtype: int64
==================================================

In [35]:
with open("report.txt", "w") as file:
    file.write("STUDENT PERFORMANCE REPORT\n")
    file.write("=" * 40 + "\n")
    file.write(f"Total Students: {len(merged)}\n")
    file.write(f"Average Math Score: {merged['math score'].mean():.2f}\n")
    file.write(f"Average Reading Score: {merged['reading score'].mean():.2f}\n")
    file.write(f"Average Writing Score: {merged['writing score'].mean():.2f}\n")
    file.write(f"Highest Percentage: {merged['Percentage'].max():.2f}\n")
    file.write(f"Lowest Percentage: {merged['Percentage'].min():.2f}\n")
    file.write(f"Pass Students: {(merged['Result']=='Pass').sum()}\n")
    file.write(f"Fail Students: {(merged['Result']=='Fail').sum()}\n")

print("Report saved successfully!")

Report saved successfully!